# Generated by Django 5.1.2 on 2025-03-09 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_filiere_alter_matiere_filiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creneauemploidutemps',
            name='jour',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='disponibilite',
            name='jour',
            field=models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi')], max_length=10),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CM', 'Cours Magistral (CM)'), ('TP', 'Travaux Dirigés (TP)'), ('TD', 'Travaux Pratiques (TD)')], max_length=2)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.enseignant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.groupe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.matiere')),
            ],
            options={
                'unique_together': {('matiere', 'groupe', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm', models.IntegerField(default=0)),
                ('tp', models.IntegerField(default=0)),
                ('td', models.IntegerField(default=0)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.groupe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.matiere')),
            ],
            options={
                'unique_together': {('matiere', 'groupe')},
            },
        ),
        migrations.CreateModel(
            name='Chevauchement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chevauchement', models.BooleanField(default=False)),
                ('groupe1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chevauchements_groupe1', to='scheduler.groupe')),
                ('groupe2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chevauchements_groupe2', to='scheduler.groupe')),
            ],
            options={
                'unique_together': {('groupe1', 'groupe2')},
            },
        ),
    ]
