# Generated by Django 5.1.7 on 2025-03-10 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('enseignant_id', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='scheduler.filiere')),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10, unique=True)),
                ('semestre', models.IntegerField()),
                ('matieres', models.ManyToManyField(to='scheduler.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi')], max_length=10)),
                ('creneau', models.IntegerField(choices=[(1, '8h-9h30'), (2, '9h45-11h15'), (3, '11h30-13h'), (4, '15h-16h30'), (5, '16h45-18h15')])),
                ('est_disponible', models.BooleanField(default=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.enseignant')),
            ],
            options={
                'unique_together': {('enseignant', 'jour', 'creneau')},
            },
        ),
        migrations.CreateModel(
            name='Chevauchement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chevauchement', models.BooleanField(default=False)),
                ('groupe1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chevauchements_groupe1', to='scheduler.groupe')),
                ('groupe2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chevauchements_groupe2', to='scheduler.groupe')),
            ],
            options={
                'unique_together': {('groupe1', 'groupe2')},
            },
        ),
        migrations.CreateModel(
            name='CreneauEmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi')], max_length=10)),
                ('creneau', models.IntegerField(choices=[(1, '8h-9h30'), (2, '9h45-11h15'), (3, '11h30-13h'), (4, '15h-16h30'), (5, '16h45-18h15')])),
                ('type', models.CharField(choices=[('CM', 'Cours Magistral (CM)'), ('TD', 'Travaux Dirigés (TD)'), ('TP', 'Travaux Pratiques (TP)')], max_length=2)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.enseignant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.groupe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.matiere')),
            ],
            options={
                'unique_together': {('groupe', 'jour', 'creneau')},
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cm', models.IntegerField(default=0)),
                ('tp', models.IntegerField(default=0)),
                ('td', models.IntegerField(default=0)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.groupe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.matiere')),
            ],
            options={
                'unique_together': {('matiere', 'groupe')},
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CM', 'Cours Magistral (CM)'), ('TP', 'Travaux Dirigés (TP)'), ('TD', 'Travaux Pratiques (TD)')], max_length=2)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.enseignant')),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.groupe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.matiere')),
            ],
            options={
                'unique_together': {('matiere', 'groupe', 'type')},
            },
        ),
    ]
